/**
 * The report. Every diagnostic issue #32 requires, per spot, as markdown.
 *
 * Pure: it takes the computed result and returns a string. It decides nothing.
 *
 * The report is the deliverable that makes the JSON checkable. shared/calibration.json
 * carries the counts a consumer needs; this carries the ones a REVIEWER needs --
 * the leave-one-out table that would expose a quietly-lengthened taxa list, the
 * per-taxon height distribution that makes diver contamination obvious on sight,
 * and the sensitivity grid that shows the corridor-wide radius is not doing any
 * work.
 */

import type { SpotResult, CalibrationRun } from './run-types.ts';
import { BINS, BIN_LABEL_DECIMALS } from './join.ts';
import {
  MAX_SINGLE_OBSERVER_SHARE,
  MIN_AMPLITUDE_RATIO,
  MIN_CONCORDANT_PAIRS,
  MIN_USABLE_BINS,
  NPS_CABRILLO_BEST_FT,
  USABLE_BIN_MIN_VISITS,
} from './config.ts';

const n = (value: number | null, digits = 2): string =>
  value === null || Number.isNaN(value) ? '—' : value.toFixed(digits);

const pct = (value: number | null): string =>
  value === null || Number.isNaN(value) ? '—' : `${(value * 100).toFixed(0)}%`;

export function renderReport(run: CalibrationRun): string {
  const out: string[] = [];

  out.push('# Calibration report');
  out.push('');
  out.push(
    'Observed sighting rates by the day\'s lowest predicted low, per spot. Generated by ' +
      '`calibration/run.ts`; do not edit by hand.',
  );
  out.push('');
  out.push('| | |');
  out.push('|---|---|');
  out.push(`| calibration version | ${run.calibrationVersion} |`);
  out.push(`| taxa config | \`calibration/target_taxa.json\` ${run.taxaVersion} |`);
  out.push(`| pulled | ${run.pulledAt} |`);
  out.push(`| source | ${run.source} |`);
  out.push(`| corpus from | ${run.corpusFrom} |`);
  out.push(`| radius | ${run.radiusKm * 1000} m, corridor-wide |`);
  out.push(`| tide station | ${run.tideStation}, datum ${run.datum}, ${run.tideYears} |`);
  out.push(`| records after filters | ${run.totalRecords} |`);
  out.push(`| visits | ${run.totalVisits} |`);
  out.push(`| content hash | \`${run.contentHash}\` |`);
  out.push('');

  out.push('## Constants');
  out.push('');
  out.push(
    'Every one of these is corridor-wide and stated a priori. None may be changed to make more ' +
      'spots publish.',
  );
  out.push('');
  out.push('| constant | value | what it decides |');
  out.push('|---|---|---|');
  out.push(
    `| bin edges | ${BINS.map((b) => b.loFt.toFixed(BIN_LABEL_DECIMALS)).join(', ')}, ` +
      `${BINS.at(-1)!.hiFt.toFixed(BIN_LABEL_DECIMALS)} | display only — the published number is ` +
      'the per-bin count |',
  );
  out.push(`| usable bin | ≥ ${USABLE_BIN_MIN_VISITS} visits | which bins the gates may read |`);
  out.push(`| minimum usable bins | ${MIN_USABLE_BINS} | refusal |`);
  out.push(`| concordant pairs | ≥ ${pct(MIN_CONCORDANT_PAIRS)} | refusal |`);
  out.push(`| amplitude ratio | ≥ ${MIN_AMPLITUDE_RATIO.toFixed(1)}× | refusal — the contamination detector |`);
  out.push(`| single-observer share | ≤ ${pct(MAX_SINGLE_OBSERVER_SHARE)} | refusal |`);
  out.push('');

  /* --- the headline table ------------------------------------------------- */

  out.push('## Result');
  out.push('');
  out.push(`| spot | visits | ${BINS.map((b) => b.label).join(' | ')} | ratio | verdict |`);
  out.push(`|---|---:|${BINS.map(() => '---:').join('|')}|---:|---|`);
  for (const spot of run.spots) {
    const cells = spot.bins.map((b) =>
      b.visits === 0 ? '—' : `${n(b.rate)} (${b.visits})${b.usable ? '' : '*'}`,
    );
    out.push(
      `| ${spot.slug} | ${spot.visits} | ${cells.join(' | ')} | ${n(spot.amplitudeRatio)} | ` +
        `${spot.publishes ? '**PUBLISH**' : 'refuse'} |`,
    );
  }
  out.push('');
  out.push(
    `\`*\` marks a bin below ${USABLE_BIN_MIN_VISITS} visits. Those are reported but no gate ` +
      'reads them.',
  );
  out.push('');

  /* --- blind check -------------------------------------------------------- */

  const cabrillo = run.spots.find((s) => s.slug === 'cabrillo-tidepools');
  out.push('## Blind check against NPS');
  out.push('');
  out.push(
    'NPS publishes, for Cabrillo: *"a tide of 0.7 or lower provides the best opportunity to ' +
      'explore the tidepools"* (nps.gov/cabr/learn/nature/tidepools.htm, read 2026-07-28). This ' +
      'is the only independent check available, so it is printed once and nothing is tuned ' +
      'against it — tuning consumes it.',
  );
  out.push('');
  if (cabrillo) {
    const bin = cabrillo.bins.find(
      (b) => NPS_CABRILLO_BEST_FT >= b.loFt && NPS_CABRILLO_BEST_FT < b.hiFt,
    );
    out.push(
      `At ${NPS_CABRILLO_BEST_FT.toFixed(1)} ft the observed rate at Cabrillo is ` +
        `**${n(bin?.rate ?? null)}** over ${bin?.visits ?? 0} visits (bin ${bin?.label ?? 'none'}), ` +
        `against ${n(cabrillo.bins[0]?.rate ?? null)} in the lowest bin.`,
    );
    out.push('');
    out.push(`> ${cabrillo.npsAgreement}`);
  } else {
    out.push('Cabrillo did not appear in this run, so the check could not be made.');
  }
  out.push('');

  /* --- per spot ----------------------------------------------------------- */

  for (const spot of run.spots) {
    out.push(`## ${spot.slug}`);
    out.push('');
    out.push(
      `${spot.publishes ? '**Publishes.**' : '**Refuses.**'} ${spot.visits} visits from ` +
        `${spot.records} records, ${spot.observers} distinct observers.`,
    );
    out.push('');

    out.push('### Filter attrition');
    out.push('');
    out.push('| stage | surviving | removed | note |');
    out.push('|---|---:|---:|---|');
    for (const stage of spot.filterStages) {
      out.push(`| ${stage.name} | ${stage.surviving} | ${stage.removed} | ${stage.note} |`);
    }
    out.push('');

    out.push('### Positional accuracy, reported not filtered');
    out.push('');
    out.push(
      `${spot.accuracy.nullAccuracy} of ${spot.accuracy.records} records ` +
        `(${pct(spot.accuracy.nullFraction)}) carry no positional accuracy at all, and ` +
        `${spot.accuracy.imprecise} (${pct(spot.accuracy.impreciseFraction)}) carry one worse ` +
        'than 100 m. These are reported separately because `acc_below` conflates them, and ' +
        'neither is filtered on.',
    );
    out.push('');

    out.push('### Bins');
    out.push('');
    out.push('| bin | visits | hits | rate | 95% interval | usable |');
    out.push('|---|---:|---:|---:|---|---|');
    for (const bin of spot.bins) {
      out.push(
        `| ${bin.label} | ${bin.visits} | ${bin.hits} | ${n(bin.rate)} | ` +
          `${bin.visits === 0 ? '—' : `[${n(bin.interval[0])}, ${n(bin.interval[1])}]`} | ` +
          `${bin.usable ? 'yes' : 'no'} |`,
      );
    }
    out.push('');
    out.push(
      spot.background === null
        ? '**Background band:** none — no bin holds ' +
            `${USABLE_BIN_MIN_VISITS} visits, so there is nothing to measure a background over.`
        : `**Background band:** [${spot.background.loFt.toFixed(2)}, ` +
            `${spot.background.hiFt.toFixed(2)}) — ${spot.background.hits} of ` +
            `${spot.background.visits} visits, ` +
            `${n(spot.background.rate)}, pooled from ${spot.background.binsPooled} ` +
            `bin${spot.background.binsPooled === 1 ? '' : 's'}. The amplitude gate's ` +
            'denominator: the highest usable bin plus every bin above it, so that no high-tide ' +
            'visit above it goes uncounted (#72).',
    );
    out.push('');

    out.push('### Refusal criteria');
    out.push('');
    out.push('| criterion | value | threshold | passed |');
    out.push('|---|---:|---:|---|');
    for (const c of spot.criteria) {
      out.push(
        `| ${c.code} | ${n(c.value)} | ${n(c.threshold)} | ${c.passed ? 'yes' : '**no**'} |`,
      );
    }
    out.push('');
    for (const c of spot.criteria) out.push(`- \`${c.code}\` — ${c.statement}`);
    out.push('');
    if (spot.nullReason) {
      out.push(`**null_reason:** ${spot.nullReason}`);
      out.push('');
    }

    out.push('### Per-taxon height distribution');
    out.push('');
    out.push(
      'The diagnostic that makes diver contamination visible without interpretation. A target ' +
        'whose median sits well above the spot\'s others is not being recorded by tidepoolers.',
    );
    out.push('');
    out.push('| taxon | role | visits | p25 | median | p75 |');
    out.push('|---|---|---:|---:|---:|---:|');
    for (const row of spot.taxonHeights) {
      out.push(
        `| ${row.name} | ${row.role} | ${row.visits} | ${n(row.p25Ft)} | ${n(row.medianFt)} | ` +
          `${n(row.p75Ft)} |`,
      );
    }
    out.push('');

    out.push('### Leave one taxon out');
    out.push('');
    out.push(
      'List length is a tuning knob and this is what makes it visible. The label is an OR across ' +
        'targets, so adding a taxon can only raise the rate and removing one can only lower it — ' +
        '"no change is justified by turning more cells green" can otherwise be satisfied silently.',
    );
    out.push('');
    out.push('| removed | hits | Δ hits | ratio | Δ ratio | flips verdict |');
    out.push('|---|---:|---:|---:|---:|---|');
    for (const row of spot.leaveOneOut) {
      out.push(
        `| ${row.removedName} | ${row.hits} | ${row.hitsDelta} | ${n(row.amplitudeRatio)} | ` +
          `${n(row.amplitudeDelta)} | ${row.flipsVerdict ? '**yes**' : 'no'} |`,
      );
    }
    out.push('');

    out.push('### Radius × accuracy sensitivity');
    out.push('');
    out.push(
      '#30 measured this at Cabrillo only, which is the richest spot by a factor of five. It is ' +
        're-run per spot rather than assumed from it. The shipped setting is ' +
        `${run.radiusKm * 1000} m with no accuracy bar.`,
    );
    out.push('');
    out.push(`| radius | acc bar | visits | ${BINS.map((b) => b.label).join(' | ')} | ratio |`);
    out.push(`|---:|---:|---:|${BINS.map(() => '---:').join('|')}|---:|`);
    for (const cell of spot.sensitivity) {
      const cells = cell.rates.map((r, i) =>
        cell.binVisits[i] === 0 ? '—' : `${n(r)} (${cell.binVisits[i]})`,
      );
      out.push(
        `| ${cell.radiusM} | ${cell.accuracyBarM ?? 'none'} | ${cell.visits} | ` +
          `${cells.join(' | ')} | ${n(cell.amplitudeRatio)} |`,
      );
    }
    out.push('');

    out.push('### Window stability');
    out.push('');
    out.push('| from | visits | ratio | any bin outside the full window\'s interval |');
    out.push('|---|---:|---:|---|');
    for (const row of spot.stability) {
      out.push(
        `| ${row.fromYear ?? 'all'} | ${row.visits} | ${n(row.amplitudeRatio)} | ` +
          `${row.outsideFullWindowInterval ? '**yes**' : 'no'} |`,
      );
    }
    out.push('');

    out.push('### Timestamp quality');
    out.push('');
    out.push(
      'Offset between a visit\'s median timestamp and the nearest predicted low. The only direct ' +
        'evidence available on whether observation times can be trusted. The predictor does not ' +
        'read the timestamp, so this is the check that ignoring it was a choice rather than a ' +
        'workaround.',
    );
    out.push('');
    out.push(
      `p10 ${n(spot.timestamps.p10Hours, 1)} h · median ${n(spot.timestamps.medianHours, 1)} h · ` +
        `p90 ${n(spot.timestamps.p90Hours, 1)} h · ` +
        `**${pct(spot.timestamps.withinBand)}** within ±${spot.timestamps.bandHours} h ` +
        `(${spot.timestamps.timedVisits} timed visits, ${spot.timestamps.untimedVisits} carrying ` +
        'a date and no time)',
    );
    out.push('');

    out.push('### Day / night');
    out.push('');
    out.push(
      `${spot.dayNight.dayVisits} of ${spot.visits} visits (${pct(spot.dayNight.dayFraction)}) ` +
        'fall on a day whose low was in daylight. Reported, never filtered on: SoCal\'s lowest ' +
        'winter lows are at night, and filtering would amputate the lowest bin. The window ' +
        'predicate in `lib/windows.ts` is daylight-clipped, so a rate partly derived from nights ' +
        'is being applied by a daytime-only rule.',
    );
    out.push('');
    if (spot.dayNight.perBin.length > 0) {
      out.push('| bin | day | night |');
      out.push('|---|---:|---:|');
      for (const row of spot.dayNight.perBin) {
        out.push(`| ${BINS[row.binIndex]?.label ?? row.binIndex} | ${row.day} | ${row.night} |`);
      }
      out.push('');
    }

    out.push('### Obscuring losses by taxon');
    out.push('');
    if (spot.obscuringLosses.length === 0) {
      out.push('No records were withheld by geoprivacy at this spot.');
    } else {
      out.push('| taxon | records withheld |');
      out.push('|---|---:|');
      for (const row of spot.obscuringLosses) {
        out.push(`| ${row.name} | ${row.obscuredRecords} |`);
      }
    }
    out.push('');
  }

  out.push('## Queries');
  out.push('');
  out.push('Every number above traces to one of these.');
  out.push('');
  for (const query of run.queries) out.push(`- \`${query}\``);
  out.push('');

  return `${out.join('\n')}\n`;
}

export type { SpotResult };
