/*
 * Every tidepool verdict, against output captured from `main` before #130
 * touched anything.
 *
 * ===========================================================================
 * What this is and why it is a committed file rather than a run
 * ===========================================================================
 *
 * #130 is a refactor: the solver, the gates and the gate states moved into
 * core/window/ and a reader is supposed to see no difference at all. "No
 * difference" is not a claim a unit test makes well -- each one asserts a
 * property somebody thought of -- so this asserts the whole grid instead, field
 * by field, against a capture taken on the parent commit.
 *
 * `__fixtures__/verdicts-20260727.json` was generated by running the PREVIOUS
 * predicate over the matrix below and writing what it returned. It is evidence,
 * not source. Regenerating it to make this pass would be the one thing that
 * makes it worthless.
 *
 * The matrix, and why each axis is there:
 *
 *   8 spots        every intertidal member, so each floor and each coordinate
 *                  is exercised -- the daylight clip differs per spot
 *   2 floors       the shipped one, and 2.5 ft. 27 July is unusable at every
 *                  real floor in the corridor, so without a deliberately
 *                  permissive one the capture would carry no `go` at all and
 *                  could not prove `go` unchanged
 *   7 days         the full grid width, from today out past the swell horizon
 *   4 swells       null, 0.4, 1.1 and 4.2 ft: unknown, calm, the real NDBC
 *                  46254 reading that morning, and over the ceiling
 *
 * 336 rows, and every one of the seven states appears in them.
 *
 * The tide is the committed 240-hour CO-OPS payload for station 9410230, which
 * every tidepool spot binds. `now` is pinned, so `isToday`, the now-clip and the
 * horizon are all reproducible.
 */
import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { evaluateWindow } from './policy';
import { gateWindowFor } from '../../core/spot/access';
import { SPOT_BY_SLUG } from '@/shared/spots.generated';
import { loadCoopsFixture, ZONE } from '../../core/window/__testing__/series';

interface GoldenRow {
  in: {
    spot: string;
    date: string;
    floorFt: number;
    ceilingFt: number;
    swellFt: number | null;
  };
  out: Record<string, unknown>;
}

const GOLDEN: GoldenRow[] = JSON.parse(
  readFileSync(fileURLToPath(new URL('./__fixtures__/verdicts-20260727.json', import.meta.url)), 'utf8'),
);

const series = loadCoopsFixture('coops-9410230-20260727-240h.json');

/** 2026-07-27 08:00 PDT. Day 0 is today; days 5 and 6 are past the swell horizon. */
const NOW_MS = Date.parse('2026-07-27T15:00:00Z');

const r6 = (n: number | null | undefined) =>
  n === null || n === undefined ? null : Number(n.toFixed(6));

const parseDate = (ymd: string) => {
  const [year, month, day] = ymd.split('-').map(Number) as [number, number, number];
  return { year, month, day };
};

/**
 * Replay one captured row and flatten the result the way the pre-refactor type
 * was shaped.
 *
 * The flattening is the point: the four fields that moved into `detail` and the
 * window geometry that became an object are read back out here and compared
 * against the names they had. If a value moved, this still compares it; if a
 * value CHANGED, this fails.
 */
function replay(row: GoldenRow) {
  const spot = SPOT_BY_SLUG[row.in.spot as keyof typeof SPOT_BY_SLUG]!;
  const date = parseDate(row.in.date);
  const result = evaluateWindow({
    series,
    date,
    floorFt: row.in.floorFt,
    swellCeilingFt: row.in.ceilingFt,
    currentSwellFt: row.in.swellFt,
    nowMs: NOW_MS,
    lat: spot.lat,
    lon: spot.lon,
    timeZone: ZONE,
    gate: gateWindowFor(row.in.spot, date, ZONE),
  });

  const { window } = result.detail;

  return {
    state: result.state,
    reason: result.reason,
    isToday: result.isToday,
    daysFromToday: result.daysFromToday,
    lowMs: result.detail.lowMs,
    lowFt: r6(result.detail.lowFt),
    nextHighMs: result.detail.nextHighMs,
    nextHighFt: r6(result.detail.nextHighFt),
    reachesFloor: result.detail.reachesFloor,
    /*
     * `above-floor` carried a zero-length window at the low's own instant before
     * #130 and carries none at all after it, so the four geometry fields are
     * read back through that placeholder. That is the ONLY shape difference in
     * this file, and it is the one the issue asked for -- the shared type no
     * longer asserts that every day has a window.
     */
    windowStartMs: window?.startMs ?? result.detail.lowMs,
    windowEndMs: window?.endMs ?? result.detail.lowMs,
    usableStartMs: window?.usableStartMs ?? result.detail.lowMs,
    usableEndMs: window?.usableEndMs ?? result.detail.lowMs,
    usableMinutes: r6(window?.usableMinutes ?? 0),
    minutesRemaining: r6(window?.minutesRemaining ?? (result.isToday ? 0 : null)),
    windowClipped: window?.seriesClipped ?? false,
    sunriseMs: result.sunriseMs,
    sunsetMs: result.sunsetMs,
    swellFt: r6(result.swellFt),
    swellKnown: result.swellKnown,
  };
}

describe('the captured grid', () => {
  it('is 336 rows covering all seven states', () => {
    // Guards the capture, not the predicate. A fixture that quietly shrank would
    // make every assertion below weaker without failing one of them.
    expect(GOLDEN).toHaveLength(336);
    const states = new Set(GOLDEN.map((r) => r.out.state));
    expect([...states].sort()).toEqual([
      'above-floor',
      'brief',
      'closed',
      'dark',
      'go',
      'swell-tbd',
      'veto',
    ]);
  });

  it('reproduces every field of every row', () => {
    /*
     * One assertion over the whole set rather than 336 `it` blocks: a failure
     * here should say WHICH rows moved and how, and vitest's diff on two arrays
     * of objects does that better than 336 test names would.
     */
    const replayed = GOLDEN.map(replay);
    expect(replayed).toEqual(GOLDEN.map((r) => r.out));
  });

  it('reproduces every reason string exactly', () => {
    // Called out separately because it is what a reader actually sees, and
    // because the sentences were reassembled from shared fragments in #130 --
    // the one part of this refactor most likely to move a space or a dash.
    for (const row of GOLDEN) {
      expect(replay(row).reason, `${row.in.spot} ${row.in.date} swell=${row.in.swellFt}`).toBe(
        row.out.reason,
      );
    }
  });
});
